# Generated by Django 4.1.2 on 2022-12-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_extensionusuario_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='extensionusuario',
            name='nacionalidad',
        ),
    ]
