# Generated by Django 4.1.2 on 2022-12-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_infoextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionusuario',
            name='nacionalidad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
