# Generated by Django 4.1.2 on 2022-10-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
